version: '3.3'
services:
  ui:
    build: ./ui
    ports:
      - '3000:3000'
    depends_on:
      - api
  test:
    build: ./ui
    environment:
      - API_HOST=api
    depends_on:
      - api
    command: npm test
  api:
    build: ./api
    ports:
      - '8081:8081'
